post: 
  description: Authenticate
  body: 
    application/json: 
      schema: tokenauthpasswordidrequest
      example: !include examples/tokenauthpasswordidrequest-example.json
  responses: 
    201: 
      body: 
        application/json: 
          schema: tokenauthnoscoperesponse
          example: !include examples/tokenauthnoscoperesponse-example.json
    401: 
      body: 
        application/json: 
          schema: tokenauthfail401aresponse
          example: !include examples/tokenauthfail401aresponse-example.json
    400: 
      body: 
        application/xml: 
          schema: badRequest
        application/json: 
          schema: ""
    403: 
      body: 
        application/xml: 
          schema: forbidden
        application/json: 
          schema: ""
    405: 
      body: 
        application/xml: 
          schema: badMethod
        application/json: 
          schema: ""
    413: 
      body: 
        application/xml: 
          schema: overLimit
        application/json: 
          schema: ""
    503: 
      body: 
        application/xml: 
          schema: serviceUnavailable
        application/json: 
          schema: ""
    404: 
      body: 
        application/xml: 
          schema: itemNotFound
        application/json: 
          schema: ""
