get: 
  description: List extensions
  responses: 
    200: 
      body: 
        application/xml: 
          schema: listExtensionsResXML
          example: !include examples/listExtensionsResXML-example.xml
        application/json: 
          schema: listExtensionsRes
          example: !include examples/listExtensionsRes-example.json
