get: 
  description: List versions
  responses: 
    200: 
      body: 
        application/json: 
          schema: dbVersionsResponse
          example: !include examples/dbVersionsResponse-example.json
    400: 
      body: 
        application/xml: 
          schema: badRequest
        application/json: 
          schema: ""
    401: 
      body: 
        application/xml: 
          schema: unauthorized
        application/json: 
          schema: ""
    403: 
      body: 
        application/xml: 
          schema: forbidden
        application/json: 
          schema: ""
    405: 
      body: 
        application/xml: 
          schema: badMethod
        application/json: 
          schema: ""
    413: 
      body: 
        application/xml: 
          schema: overLimit
        application/json: 
          schema: ""
    422: 
      body: 
        application/xml: 
          schema: unprocessableEntity
        application/json: 
          schema: ""
    500: 
      body: 
        application/xml: 
          schema: instanceFault
        application/json: 
          schema: ""
    501: 
      body: 
        application/xml: 
          schema: notImplemented
        application/json: 
          schema: ""
    503: 
      body: 
        application/xml: 
          schema: serviceUnavailable
        application/json: 
          schema: ""
    404: 
      body: 
        application/xml: 
          schema: itemNotFound
        application/json: 
          schema: ""
